### ISSUE TITLE
[BackEnd] '/login_data'에 2번 접근시 서버가 죽습니다.

### ISSUE THREAD

**Issue by rasauq1122** [O-nlogn/Hotel_Management_System#4]
```
0|server   |     at Protocol.handshake (/home/rasauq1122/HMS/node_modules/mysql/lib/protocol/Protocol.js:51:23)
0|server   |     at Connection.connect (/home/rasauq1122/HMS/node_modules/mysql/lib/Connection.js:116:18)
0|server   |     at IncomingMessage.<anonymous> (/home/rasauq1122/HMS/router/main.js:50:22)
0|server   |     at IncomingMessage.emit (events.js:203:15)
0|server   |     at endReadableNT (_stream_readable.js:1145:12)
0|server   |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'PROTOCOL_ENQUEUE_HANDSHAKE_TWICE', fatal: false }
0|server   | { Error: Cannot enqueue Handshake after already enqueuing a Handshake.
0|server   |     at Protocol._validateEnqueue (/home/rasauq1122/HMS/node_modules/mysql/lib/protocol/Protocol.js:221:16)
0|server   |     at Protocol._enqueue (/home/rasauq1122/HMS/node_modules/mysql/lib/protocol/Protocol.js:138:13)
0|server   |     at Protocol.handshake (/home/rasauq1122/HMS/node_modules/mysql/lib/protocol/Protocol.js:51:23)
0|server   |     at Connection.connect (/home/rasauq1122/HMS/node_modules/mysql/lib/Connection.js:116:18)
0|server   |     at IncomingMessage.<anonymous> (/home/rasauq1122/HMS/router/main.js:50:22)
0|server   |     at IncomingMessage.emit (events.js:203:15)
0|server   |     at endReadableNT (_stream_readable.js:1145:12)
0|server   |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'PROTOCOL_ENQUEUE_HANDSHAKE_TWICE', fatal: false }
```
다음과 같은 메시지를 띄우며 서버가 죽습니다. 
웹서핑을 통해 알아본 후 해결해보도록 하겠습니다.

**Comment by rasauq1122** [comment]
해결하였습니다.
